
package sapplet;

import helper.WebController;
import java.applet.Applet;
import java.applet.AppletStub;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Home extends javax.swing.JApplet implements  AppletStub {

    /**
     * Initializes the applet Home
     */
    @Override
    public void init() {
        
        
         setSize(1100,550);
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonToUser = new javax.swing.JButton();
        ButtonToVote = new javax.swing.JButton();
        ButtonToAdmin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        webC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        searchOnWeb = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(788, 513));

        jPanel1.setLayout(null);

        ButtonToUser.setText("User");
        ButtonToUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonToUserActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonToUser);
        ButtonToUser.setBounds(455, 112, 57, 32);

        ButtonToVote.setText("Vote Register");
        ButtonToVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonToVoteActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonToVote);
        ButtonToVote.setBounds(528, 112, 120, 32);

        ButtonToAdmin.setText("Admin");
        ButtonToAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonToAdminActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonToAdmin);
        ButtonToAdmin.setBounds(362, 112, 70, 32);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel2.setText("SOA for High Dimentional Private Data ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 20, 496, 29);

        jLabel1.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel1.setText("Home Page");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(215, 68, 83, 17);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 250, 560, 220);

        webC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webCActionPerformed(evt);
            }
        });
        jPanel1.add(webC);
        webC.setBounds(200, 210, 190, 24);

        jLabel3.setText("Search on web: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 210, 91, 16);

        searchOnWeb.setText("Go");
        searchOnWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOnWebActionPerformed(evt);
            }
        });
        jPanel1.add(searchOnWeb);
        searchOnWeb.setBounds(410, 210, 45, 30);

        jLabel4.setText("Enter the topic below you want to search on web");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 180, 290, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonToAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonToAdminActionPerformed
        jPanel1.setVisible(false);
        Thread t1=new Thread(new Runnable() {
    @Override
    public void run() {
       try {
        
        Class applet2 = Class.forName("sapplet.Admin");//new address
        Applet appletToLoad = (Applet)applet2.newInstance();
        appletToLoad.setStub(Home.this);
        
        add(appletToLoad);
        appletToLoad.init();
        appletToLoad.start();
        validate();//validate
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
});
    t1.start();
        
    }//GEN-LAST:event_ButtonToAdminActionPerformed

    private void ButtonToUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonToUserActionPerformed
        // TODO add your handling code here:
         jPanel1.setVisible(false);
        Thread t1=new Thread(new Runnable() {
    @Override
    public void run() {
       try {
        
        Class applet2 = Class.forName("sapplet.User");//new address
        Applet appletToLoad = (Applet)applet2.newInstance();
        appletToLoad.setStub(Home.this);
        
        add(appletToLoad);
        appletToLoad.init();
        appletToLoad.start();
        validate();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
});
    t1.start();
    }//GEN-LAST:event_ButtonToUserActionPerformed

    private void ButtonToVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonToVoteActionPerformed
        // TODO add your handling code here:
         jPanel1.setVisible(false);
        Thread t1=new Thread(new Runnable() {
    @Override
    public void run() {
       try {
        
        Class applet2 = Class.forName("sapplet.Vote");
        Applet appletToLoad = (Applet)applet2.newInstance();
        appletToLoad.setStub(Home.this);
        
        add(appletToLoad);
        appletToLoad.init();
        appletToLoad.start();
        validate();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
});
    t1.start();
    }//GEN-LAST:event_ButtonToVoteActionPerformed

    private void webCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_webCActionPerformed

    private void searchOnWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOnWebActionPerformed
      ArrayList<String> links =new ArrayList<String>();
        WebController wc=new WebController();
      
      String keyword=webC.getText();
        try {
            links=wc.GetsearchEngineLinks(keyword);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextArea1.setText("\t\t"+"Important Links to study the Topic: "+keyword+"\n"+
        "\t\t---------------------------------------------------------\n");
        for (String link : links) {
            jTextArea1.append(link+"\n");
        }
    }//GEN-LAST:event_searchOnWebActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonToAdmin;
    private javax.swing.JButton ButtonToUser;
    private javax.swing.JButton ButtonToVote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton searchOnWeb;
    private javax.swing.JTextField webC;
    // End of variables declaration//GEN-END:variables

    @Override
    public void appletResize(int i, int i1) {
         resize( i, i1 );
    }


}
