
package sapplet;

import helper.User;
import java.applet.Applet;
import java.applet.AppletStub;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class signup extends javax.swing.JApplet implements AppletStub{
   
   ArrayList<User> users=new ArrayList<>();//users list
    
    

  
    /**
     * Initializes the applet signup
     */
    @Override
     public void init() {
          setSize(1100,550);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Lname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SSN = new javax.swing.JTextField();
        Fname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        signupSubmit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();

        setMaximumSize(new java.awt.Dimension(788, 513));
        setMinimumSize(new java.awt.Dimension(788, 513));

        jPanel1.setLayout(null);

        jLabel7.setText("Gender");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 255, 70, 14);

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel2.setText("Sign up");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(257, 46, 56, 23);
        jPanel1.add(age);
        age.setBounds(156, 214, 325, 20);

        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 179, 70, 14);

        jLabel3.setText("First Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 109, 80, 14);
        jPanel1.add(Email);
        Email.setBounds(156, 290, 325, 20);

        jLabel10.setText("Phone No.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 369, 70, 14);

        Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameActionPerformed(evt);
            }
        });
        jPanel1.add(Lname);
        Lname.setBounds(156, 138, 325, 20);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setText("SOA for High Dimentional Private Data ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(56, 11, 496, 29);
        jPanel1.add(SSN);
        SSN.setBounds(156, 80, 325, 20);

        Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameActionPerformed(evt);
            }
        });
        jPanel1.add(Fname);
        Fname.setBounds(156, 106, 325, 20);

        jLabel9.setText("Password");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 331, 70, 14);

        jLabel6.setText("Age");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 217, 60, 14);
        jPanel1.add(gender);
        gender.setBounds(156, 252, 325, 20);

        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 144, 80, 14);

        signupSubmit.setText("Submit");
        signupSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(signupSubmit);
        signupSubmit.setBounds(222, 400, 90, 23);

        jLabel11.setText("SSN");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 86, 40, 14);
        jPanel1.add(Address);
        Address.setBounds(156, 176, 325, 20);

        jLabel8.setText("User name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 293, 80, 14);
        jPanel1.add(phone);
        phone.setBounds(156, 366, 325, 20);
        jPanel1.add(password);
        password.setBounds(156, 328, 325, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameActionPerformed

    private void signupSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupSubmitActionPerformed
          ObjectInputStream istream=null;
        try {
        //test user with id and pwd
       istream=new ObjectInputStream(new FileInputStream("user.txt"));//read users
    } catch (FileNotFoundException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        users=(ArrayList<helper.User>) istream.readObject();
    } catch (IOException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }  
    //create new user
         User u1=new User(SSN.getText(),Fname.getText(),Lname.getText(),Address.getText(),age.getText(),gender.getText(),Email.getText(),password.getText(),phone.getText());
       users.add(u1);
         
           ObjectOutputStream ostream=null;
        try {
            ostream = new ObjectOutputStream(new FileOutputStream("user.txt"));//user file
        } catch (FileNotFoundException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ostream.writeObject(users);//write users to file
            
//        this.setVisible(false);
//        new Login().setVisible(true);
 jPanel1.setVisible(false);
        Thread t1=new Thread(new Runnable() {
    @Override
    public void run() {
       try {
        
        Class applet2 = Class.forName("sapplet.User");//new applet
        Applet appletToLoad = (Applet)applet2.newInstance();
        appletToLoad.setStub(signup.this);
        
        add(appletToLoad);
        appletToLoad.init();
        appletToLoad.start();
        validate();//validate new applet
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
});
    t1.start();
        } catch (IOException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signupSubmitActionPerformed

    private void LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField SSN;
    private javax.swing.JTextField age;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JButton signupSubmit;
    // End of variables declaration//GEN-END:variables

    @Override
    public void appletResize(int width, int height) {
        resize( width, height );
      }
}
