
package sapplet;

import helper.Voter;
import java.applet.Applet;
import java.applet.AppletStub;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Vote extends javax.swing.JApplet implements AppletStub{
       
       ArrayList<Voter> voters=new ArrayList<>();//voters list
    

    @Override
    public void init() {
        setSize(1100,550);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        SSNVoter = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        zipcode = new javax.swing.JTextField();
        VFname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        VLname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SubmitVoter = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Gender = new javax.swing.JTextField();
        GoToHome = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(788, 513));

        jPanel1.setLayout(null);
        jPanel1.add(SSNVoter);
        SSNVoter.setBounds(131, 120, 218, 20);
        jPanel1.add(Age);
        Age.setBounds(131, 215, 218, 20);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setText("SOA for High Dimentional Private Data ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(104, 11, 496, 29);

        jLabel6.setText("Gender");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(63, 263, 50, 14);

        jLabel4.setText("Age");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(79, 218, 40, 14);
        jPanel1.add(zipcode);
        zipcode.setBounds(131, 298, 218, 20);

        VFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VFnameActionPerformed(evt);
            }
        });
        jPanel1.add(VFname);
        VFname.setBounds(131, 146, 218, 20);

        jLabel7.setText("SSN");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(78, 123, 40, 14);
        jPanel1.add(VLname);
        VLname.setBounds(131, 184, 218, 20);

        jLabel3.setText("Voter's Last name ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 184, 110, 14);

        SubmitVoter.setText("Submit");
        SubmitVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitVoterActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitVoter);
        SubmitVoter.setBounds(213, 336, 100, 23);

        jLabel8.setText("Zip Code");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(56, 298, 60, 14);

        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });
        jPanel1.add(Gender);
        Gender.setBounds(131, 260, 218, 20);

        GoToHome.setText("Home");
        GoToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToHomeActionPerformed(evt);
            }
        });
        jPanel1.add(GoToHome);
        GoToHome.setBounds(436, 51, 80, 23);

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel1.add(Logout);
        Logout.setBounds(535, 51, 80, 23);

        jLabel2.setText("Voter's First Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 149, 110, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(309, 309, 309))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VFnameActionPerformed

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderActionPerformed

    private void SubmitVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitVoterActionPerformed
                  ObjectInputStream istream=null;
        try {
        //test user with id and pwd
       istream=new ObjectInputStream(new FileInputStream("voters.txt"));//read voters
    } catch (FileNotFoundException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        voters=(ArrayList<Voter>) istream.readObject();
    } catch (IOException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }    
        Voter v1=new Voter(SSNVoter.getText(),VFname.getText(),VLname.getText(),Age.getText(),Gender.getText(),zipcode.getText());
       voters.add(v1);
  
           ObjectOutputStream ostream=null;
        try {
            ostream = new ObjectOutputStream(new FileOutputStream("voters.txt"));//write voters
        } catch (FileNotFoundException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ostream.writeObject(voters);//write list
            JOptionPane.showMessageDialog(null, "Added successfully");
//        this.setVisible(false);
//        new Login().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_SubmitVoterActionPerformed

    private void GoToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToHomeActionPerformed
        // TODO add your handling code here:
         jPanel1.setVisible(false);
        Thread t1=new Thread(new Runnable() {
    @Override
    public void run() {
       try {
        
        Class applet2 = Class.forName("sapplet.Home");//new applet
        Applet appletToLoad = (Applet)applet2.newInstance();
        appletToLoad.setStub(Vote.this);
        
        add(appletToLoad);
        appletToLoad.init();
        appletToLoad.start();
        validate();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
});
    t1.start();
    }//GEN-LAST:event_GoToHomeActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
         jPanel1.setVisible(false);
        Thread t1=new Thread(new Runnable() {
    @Override
    public void run() {
       try {
        
        Class applet2 = Class.forName("sapplet.User");
        Applet appletToLoad = (Applet)applet2.newInstance();
        appletToLoad.setStub(Vote.this);
        
        add(appletToLoad);
        appletToLoad.init();
        appletToLoad.start();
        validate();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
});
    t1.start();
    }//GEN-LAST:event_LogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Gender;
    private javax.swing.JButton GoToHome;
    private javax.swing.JButton Logout;
    private javax.swing.JTextField SSNVoter;
    private javax.swing.JButton SubmitVoter;
    private javax.swing.JTextField VFname;
    private javax.swing.JTextField VLname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField zipcode;
    // End of variables declaration//GEN-END:variables

    @Override
    public void appletResize(int width, int height) {
    }
}
